// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: userlibrary.proto

package userlibrarypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запись «пользователь-владеет-книгой»
type UserBook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                       // ID записи
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // ID пользователя
	BookId        string                 `protobuf:"bytes,3,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"` // ID книги из каталога
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBook) Reset() {
	*x = UserBook{}
	mi := &file_userlibrary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBook) ProtoMessage() {}

func (x *UserBook) ProtoReflect() protoreflect.Message {
	mi := &file_userlibrary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBook.ProtoReflect.Descriptor instead.
func (*UserBook) Descriptor() ([]byte, []int) {
	return file_userlibrary_proto_rawDescGZIP(), []int{0}
}

func (x *UserBook) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserBook) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserBook) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

// Запросы
type AssignBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookId        string                 `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignBookRequest) Reset() {
	*x = AssignBookRequest{}
	mi := &file_userlibrary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignBookRequest) ProtoMessage() {}

func (x *AssignBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userlibrary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignBookRequest.ProtoReflect.Descriptor instead.
func (*AssignBookRequest) Descriptor() ([]byte, []int) {
	return file_userlibrary_proto_rawDescGZIP(), []int{1}
}

func (x *AssignBookRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignBookRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type UnassignBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookId        string                 `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnassignBookRequest) Reset() {
	*x = UnassignBookRequest{}
	mi := &file_userlibrary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnassignBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnassignBookRequest) ProtoMessage() {}

func (x *UnassignBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userlibrary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnassignBookRequest.ProtoReflect.Descriptor instead.
func (*UnassignBookRequest) Descriptor() ([]byte, []int) {
	return file_userlibrary_proto_rawDescGZIP(), []int{2}
}

func (x *UnassignBookRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UnassignBookRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type ListUserBooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserBooksRequest) Reset() {
	*x = ListUserBooksRequest{}
	mi := &file_userlibrary_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserBooksRequest) ProtoMessage() {}

func (x *ListUserBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userlibrary_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserBooksRequest.ProtoReflect.Descriptor instead.
func (*ListUserBooksRequest) Descriptor() ([]byte, []int) {
	return file_userlibrary_proto_rawDescGZIP(), []int{3}
}

func (x *ListUserBooksRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Ответы
type AssignBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *UserBook              `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignBookResponse) Reset() {
	*x = AssignBookResponse{}
	mi := &file_userlibrary_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignBookResponse) ProtoMessage() {}

func (x *AssignBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userlibrary_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignBookResponse.ProtoReflect.Descriptor instead.
func (*AssignBookResponse) Descriptor() ([]byte, []int) {
	return file_userlibrary_proto_rawDescGZIP(), []int{4}
}

func (x *AssignBookResponse) GetEntry() *UserBook {
	if x != nil {
		return x.Entry
	}
	return nil
}

type UnassignBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnassignBookResponse) Reset() {
	*x = UnassignBookResponse{}
	mi := &file_userlibrary_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnassignBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnassignBookResponse) ProtoMessage() {}

func (x *UnassignBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userlibrary_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnassignBookResponse.ProtoReflect.Descriptor instead.
func (*UnassignBookResponse) Descriptor() ([]byte, []int) {
	return file_userlibrary_proto_rawDescGZIP(), []int{5}
}

func (x *UnassignBookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListUserBooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*UserBook            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserBooksResponse) Reset() {
	*x = ListUserBooksResponse{}
	mi := &file_userlibrary_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserBooksResponse) ProtoMessage() {}

func (x *ListUserBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userlibrary_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserBooksResponse.ProtoReflect.Descriptor instead.
func (*ListUserBooksResponse) Descriptor() ([]byte, []int) {
	return file_userlibrary_proto_rawDescGZIP(), []int{6}
}

func (x *ListUserBooksResponse) GetEntries() []*UserBook {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_userlibrary_proto protoreflect.FileDescriptor

const file_userlibrary_proto_rawDesc = "" +
	"\n" +
	"\x11userlibrary.proto\x12\vuserlibrary\"L\n" +
	"\bUserBook\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\abook_id\x18\x03 \x01(\tR\x06bookId\"E\n" +
	"\x11AssignBookRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\tR\x06bookId\"G\n" +
	"\x13UnassignBookRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\tR\x06bookId\"/\n" +
	"\x14ListUserBooksRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"A\n" +
	"\x12AssignBookResponse\x12+\n" +
	"\x05entry\x18\x01 \x01(\v2\x15.userlibrary.UserBookR\x05entry\"0\n" +
	"\x14UnassignBookResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"H\n" +
	"\x15ListUserBooksResponse\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.userlibrary.UserBookR\aentries2\x90\x02\n" +
	"\x12UserLibraryService\x12M\n" +
	"\n" +
	"AssignBook\x12\x1e.userlibrary.AssignBookRequest\x1a\x1f.userlibrary.AssignBookResponse\x12S\n" +
	"\fUnassignBook\x12 .userlibrary.UnassignBookRequest\x1a!.userlibrary.UnassignBookResponse\x12V\n" +
	"\rListUserBooks\x12!.userlibrary.ListUserBooksRequest\x1a\".userlibrary.ListUserBooksResponseB^Z\\github.com/OshakbayAigerim/read_space/user_library_service/proto/userlibrarypb;userlibrarypbb\x06proto3"

var (
	file_userlibrary_proto_rawDescOnce sync.Once
	file_userlibrary_proto_rawDescData []byte
)

func file_userlibrary_proto_rawDescGZIP() []byte {
	file_userlibrary_proto_rawDescOnce.Do(func() {
		file_userlibrary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userlibrary_proto_rawDesc), len(file_userlibrary_proto_rawDesc)))
	})
	return file_userlibrary_proto_rawDescData
}

var file_userlibrary_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_userlibrary_proto_goTypes = []any{
	(*UserBook)(nil),              // 0: userlibrary.UserBook
	(*AssignBookRequest)(nil),     // 1: userlibrary.AssignBookRequest
	(*UnassignBookRequest)(nil),   // 2: userlibrary.UnassignBookRequest
	(*ListUserBooksRequest)(nil),  // 3: userlibrary.ListUserBooksRequest
	(*AssignBookResponse)(nil),    // 4: userlibrary.AssignBookResponse
	(*UnassignBookResponse)(nil),  // 5: userlibrary.UnassignBookResponse
	(*ListUserBooksResponse)(nil), // 6: userlibrary.ListUserBooksResponse
}
var file_userlibrary_proto_depIdxs = []int32{
	0, // 0: userlibrary.AssignBookResponse.entry:type_name -> userlibrary.UserBook
	0, // 1: userlibrary.ListUserBooksResponse.entries:type_name -> userlibrary.UserBook
	1, // 2: userlibrary.UserLibraryService.AssignBook:input_type -> userlibrary.AssignBookRequest
	2, // 3: userlibrary.UserLibraryService.UnassignBook:input_type -> userlibrary.UnassignBookRequest
	3, // 4: userlibrary.UserLibraryService.ListUserBooks:input_type -> userlibrary.ListUserBooksRequest
	4, // 5: userlibrary.UserLibraryService.AssignBook:output_type -> userlibrary.AssignBookResponse
	5, // 6: userlibrary.UserLibraryService.UnassignBook:output_type -> userlibrary.UnassignBookResponse
	6, // 7: userlibrary.UserLibraryService.ListUserBooks:output_type -> userlibrary.ListUserBooksResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_userlibrary_proto_init() }
func file_userlibrary_proto_init() {
	if File_userlibrary_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userlibrary_proto_rawDesc), len(file_userlibrary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userlibrary_proto_goTypes,
		DependencyIndexes: file_userlibrary_proto_depIdxs,
		MessageInfos:      file_userlibrary_proto_msgTypes,
	}.Build()
	File_userlibrary_proto = out.File
	file_userlibrary_proto_goTypes = nil
	file_userlibrary_proto_depIdxs = nil
}
